name: Build FFmpeg on macOS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pkg-config gnutls aom aribb24 libbluray dav1d harfbuzz jpeg-xl opus x265 x264

      - name: Clone FFmpeg source code
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-source
          cd ffmpeg-source

      - name: Build FFmpeg
        working-directory: ffmpeg-source
        run: |
          clang --version
          ./configure --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libopus --enable-libx265 --enable-libx264
          make
